### ISSUE TITLE
Number of distinct color sets

### ISSUE THREAD

**Issue by mohsenzakeri** [jermp/fulgor#38]
Hi @jermp,

I hope you are doing well.  I have a question about the number of colors reported by the `fulgor stats` subcommand.  If I build two `fulgor` indexes with the same value of `k` (e.g., k=31), but different value for `m` (e.g., m=15 and m=20), should I expect to observe the same `number of distinct color sets` reported by the `stats` subcommand?  However, in my experiment, this was not the case when building the index on 200 _Bacillus_subtilis_ genomes.  The reported number of distinct colors are as follows:

k=31, m=25: 718026
k=31, m=20: 718033
k=31, m=15: 718025

I used the latest version from the `main` branch to get this result.  I tried the first version of `fulgor` observed the same issue.  However, another problem was that I saw slightly different number of colors compared to this version (e.g., for k=31 and m=25 with the first version, the number of colors is 718010).  Is that behavior also expected?

Thank you in advance for your response to this issue.

Best,
Mohsen

**Comment by jermp** [comment]
Hi Mohsen! I'm doing fine here, and hope you're doing well as well :)

So, the different number of color sets you saw is due to GGCAT not necessarily computing **maximal** unitigs. For efficiency reasons, it may compute unitigs that are not maximal. See this issue that I opened over a year ago https://github.com/algbio/ggcat/issues/24. However, you should not worry about this since the correctness of Fulgor is not impacted in anyway: what is important is that the number of kmers is the same and the number of colors (documents).

Hope this clarifies.
Best,
-Giulio

**Comment by mohsenzakeri** [comment]
Thank you for your very quick response! :)  It makes total sense now.  I really appreciate the insight regarding GGCAT and the non-maximal unitigs and I'm glad it doesn't affect the correctness of fulgor.
Best,
Mohsen
